### ISSUE TITLE
No version information in PURL

### ISSUE THREAD

**Issue by anthonyharrison** [scanoss/purl2cpe#11]
Any reason why the PURL references don't contain the version information which is contained within the cpe entry?

**Comment by scanossmining** [comment]
@anthonyharrison The process of pairing PURLs to CPEs is done at this moment manually by our team of curators. We're only pairing the unversioned purls to all versions of a CPE in order to speed up the pairing process. Adding also versions to each purl will require a lot more time to process all the changes, since we cannot automatically use the version from inside the CPE and attach it to the purl. In the future we might add also versions to the purls and change the format of the dataset
